steps:
  - label: ":construction_worker: Build"
    command: "scripts/build.sh"
    key: build
    artifact_paths:
      - "build/*"

  - label: ":white_check_mark: Test"
    command: "scripts/run_ut.sh"
    key: test
    depends_on: build
    plugins:
      - artifacts#v1.1.0:
          download: "build/*"  # 下载上一步的构建物

    plugins:
      - junit-xml#v2.0.0:
          files: "build/test-results.xml"

    artifact_paths:
      - "build/test-results.xml"
