steps:
  - label: ":construction_worker: Build"
    command: "scripts/build.sh"
    key: build
    artifact_paths:
      - "build/*"

  - wait: ~

  - label: ":white_check_mark: Test"
    command: "scripts/run_ut.sh"
    key: test
    depends_on: build
    plugins:
      - artifacts#v1.1.0:
          download: "build/*"  # download the artifacts produced by last step

      - test-collector#v1.0.0:
          files: "build/junit_output.xml"
          format: "junit"

    artifact_paths:
      - "build/junit_output.xml"